# Session 4: Ethics
#### <span style="color:#E45201;">How do we consider Ethics within GIScience, including (but not limited to) the Locus Charter</span> {-}

#### Organisers {-}
- Dr [Nick Bearman](https://www.geospatialtrainingsolutions.co.uk/about-us/), *Geospatial Training Solutions, University College London* 

#### Abstract {-}
This session will consider the recent developments in ethics within a GIScience setting. A major change recently is the development of the [Locus Charter](https://t.co/rjvkagqJip), an ethical framework helping to promote understanding of risks and solutions relating to uses of location data, particularly with reference to improving standards and the public interest. While the Locus Charter has been initially designed around commercial work and the public sector, there are clear applications to wider uses of location data and ethical implications of this in academia and other areas. Currently this is a 'call for interest' so if you are interested, no matter how undeveloped your idea is, please do get in touch.

#### Instructions for Authors {-}
Please submit abstracts of no more than 250 words for 15 minutes presentations to nick@geospatialtrainingsolutions.co.uk before **March 18th, 2022**.
