# Session 2: Deep learning 
#### <span style="color:#E45201;">Deep learning applications in geography</span> {-}

#### Organisers {-}
- Dr [Stefano De Sabbata](https://sdesabbata.github.io/), *University of Leicester*
- Dr [Andrea Ballatore](https://aballatore.space/), *King’s College London, University of London*
- Dr [Godwin Yeboah](https://warwick.ac.uk/fac/arts/schoolforcross-facultystudies/igsd/about/people/gyeboah/), *University of Warwick*

#### Abstract {-}
Deep learning approaches are becoming an integral part of the GIScience toolbox. [Li *et al*. 2021](https://doi.org/10.1080/13658816.2021.1912347) combined graph convolutional networks and recurrent neural networks to model human activity intensity including interactions in physical and social space. [Liu and De Sabbata 2021](https://doi.org/10.1016/j.compenvurbsys.2020.101583) developed a graph-based semi-supervised approach to classify social media posts based on their text, image and spatio-temporal information. [Palmer *et al*. 2021](https://doi.org/10.1038/s41598-021-84572-4) applied computer vision approaches to the Liverpool 360º Street View dataset to explore the exposure to fast food, gambling and alcohol advertisements. [Zheng and Sieber 2022](https://doi.org/10.1111/tgis.12869) explore the interaction between artificial intelligence and human intervention in the development of smart cities. 

Following up on last year’s successful session on deep learning approaches in GIScience, this year we aim to continue to explore the application of these new tools in geography. Sitting at the crossroads between geographical enquiry and scientific and technological development in information and computer science, GIScience has always been a forum for both the application of new technologies in geography and the geographical critique of those same tools. Continuing this tradition, this session aims to bring together contributions that showcase the applications of deep learning tools in any form of geographic and cartographic enquiry, contributions that demonstrate novel spatially-aware deep learning approaches and contributions that aim to critically enquire the implications of the use of these new tools in geography. 

#### Instructions for Authors {-}
Please submit abstracts of no more than 250 words for 15 minutes presentations to s.desabbata@le.ac.uk before **March 18th, 2022**.
