# Session 1: Safety and emergency services 
#### <span style="color:#E45201;">Innovative GI methods in safety and emergency services research </span> {-}

#### Organisers {-}
- Prof [Vania Ceccato](https://www.kth.se/profile/vace?l=en), *KTH Royal Institute of Technology* 

#### Abstract {-}
The use of geographical information (GI) in safety and emergency services research is linked to the technological development of GI-based techniques. In addition, geographical information systems (GIS) have made geographical analyses of data possible for a wide number of users, facilitating the integration of many types of data into a common spatial framework. The value of geographical analysis is becoming even greater when enhanced with spatial statistical techniques, artificial intelligence (AI) methods and new types of data, from remote sensing  data to crowdsourced data. In this session, we present examples of the use and the integration of GI in safety and emergency services research. We explore the use of remote sensing data in crime research, the analysis of AI patterns of safety perceptions and the use of Twitter data in policing and emergency services research. 

#### Instructions for Authors {-}
Please submit abstracts of no more than 250 words for 15 minutes presentations to vania.ceccato@abe.kth.se before **March 18th, 2022**.
